#pragma config(Sensor, in1,    progamSelec,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rbEncoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  lbEncoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rfEncoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  lfEncoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  raEncoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl11, downLimit,      sensorTouch)
#pragma config(Sensor, dgtl12, upLimit,        sensorTouch)
#pragma config(Motor,  port2,           rightBack,     tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, dgtl1, 0)
#pragma config(Motor,  port3,           leftBack,      tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, dgtl3, 1000)
#pragma config(Motor,  port4,           rightFront,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl5, 1000)
#pragma config(Motor,  port5,           leftFront,     tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl7, 1000)
#pragma config(Motor,  port6,           leftArm,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           rightArm,      tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl9, 1000)
#pragma config(Motor,  port8,           leftArm,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           rightArm,      tmotorServoContinuousRotation, openLoop, encoder, encoderPort, dgtl9, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                - ADVANCED Single Joystick Control -                                *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses a single joystick, either right or left (this is configurable below) to drive   *|
|*  the robot.                                                                                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*    3)  'abs(z)' is the ABSOLUTE VALUE of 'z'.                                                      *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{
  int joy_left;            // will hold the X value of the analog stick (choices below)
  int joy_right;            // will hold the Y value of the analog stick (choices below)
  int threshold = 10;	// helps to eliminate 'noise' from a joystick that isn't perfectly at (0,0)


  while(1 == 1)
  {
    joy_left = vexRT[Ch3];   // This is the RIGHT analog stick.  For LEFT, change 'Ch1' to 'Ch4'.
    joy_right = vexRT[Ch2];   // This is the RIGHT analog stick.  For LEFT, change 'Ch2' to 'Ch3'.

    // Forward, and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is POSITIVE)

    if((SensorValue(downLimit) == 1) && (motor[rightArm] > 0))
    {
    	motor[rightArm] = 0;
    	motor[leftArm] = 0;
 		}
 		if((SensorValue(upLimit) == 1) && (motor[rightArm] > 0))
    {
    	motor[rightArm] = 0;
    	motor[leftArm] = 0;
 		}

    if((abs(joy_left) > threshold) && (abs(joy_left) > 0))
    {
      motor[leftFront]  = (joy_left);
      motor[leftBack] = (joy_left);
    }
    // Backwards and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is NEGATIVE)
    if((abs(joy_right) > threshold) && (abs(joy_right) > 0))
    {
     	motor[rightFront] = (joy_right);
     	motor[rightBack] = (joy_right);
    }
    // Turning in place: (abs(X) is above the threshold, abs(Y) is below the threshold)
 		if ((abs(joy_right) < threshold))
 		{
 			motor[rightFront] = 0;
 			motor[rightBack] = 0;
 		}
 			if ((abs(joy_left) < threshold))
 		{
 			motor[leftFront] = 0;
 			motor[leftBack] = 0;
 		}
    // Standing still: (both abs(X) and abs(Y) are below the threshold)
    //else
    //{
     // motor[leftMotor]  = 0;
     // motor[rightMotor] = 0;
    //}
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
